

networks:
    net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.100.0.0/16

services:
    nginx:
        image: nginx:alpine
        container_name: "${CONTAINER_PREFIX}_nginx"
        restart: unless-stopped
        tty: true
        ports:
            - "${NGINX_PORT}:8000"
        volumes:
            - ./src:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - db
        networks:
            - ${NETWORK}

    db:
        image: mysql:8
        container_name: "${CONTAINER_PREFIX}_mysql"
        restart: unless-stopped
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "${DB_PORT}:3306"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        networks:
            - ${NETWORK}

    php:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_php:latest
        container_name: "${CONTAINER_PREFIX}_php"
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        #command: bash -c "php artisan serve | npm run watch "
        volumes:
            - ./src:/var/www/app
        ports:
            # - "${PHP_PORT}:9000"
            - "${NPM_PORT}:3000"
            - "8080:8080"
            - "2525:2525"
        networks:
            - ${NETWORK}

    redis:
        image: redis:alpine
        container_name: "${CONTAINER_PREFIX}_redis"
        ports:
            - "${REDIS_PORT}:6379"
        networks:
            - ${NETWORK}

